name: Helm Charts

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [aws-cli, azure-cli, buildah, commuter, dockerizer, gcloud-cli, jupyter-lab, jupyter-notebook, kaniko, papermill, streamlit, tensorboard, vscode]

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-python@v2.0.1
        with:
          python-version: 3.7
      - name: test
        run: |
          export PATH=$HOME/.local/bin:/usr/local/bin:$PATH
          pip3 install -U polyaxon

          COMPONENTS=${{ matrix.component }}/*

          for f in $COMPONENTS
          do
          if [[ "$f" != *\.* ]]
          then
            polyaxon check -f ${{ matrix.component }}/$f
          fi
          done
