name: Test Components

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    container: docker://polyaxon/polyaxon-cli
    strategy:
      matrix:
        component: [aws-cli, azure-cli, buildah, commuter, dockerizer, gcloud-cli, jupyterlab, notebook, kaniko, papermill, streamlit, tensorboard, vscode]

    steps:
      - uses: actions/checkout@v2
      - run: pip install -U polyaxon
      - name: test
        run: |
          COMPONENTS=hub/${{ matrix.component }}/*.yaml
          echo "checking components: $COMPONENTS"

          for f in $COMPONENTS; do
          if [[ -r "$f" ]]; then
            echo "checking component: $f"
            polyaxon check -f $f --lint
          fi
          done
